### PR TITLE
Version 2.0

### PR DESCRIPTION
**Pull request by mecachisenros**
Summary:

* Plugin refactored
* Moved Settings page to Woocommerce -> Settings -> CiviCRM (Tab)
* Added translation support
* Added option to sync Customer/Contact address
* Added option to sync Customer/Contact billing phone
* Added option to sync Customer/Contact billing email
* Added option to replace Woocommerce State/County list with CiviCRM State/Province list
* Added 'woocommerce_civicrm_contribution_create_params' filter
* Added 'woocommerce_civicrm_contribution_update_params' filter
* Added 'woocommerce_civicrm_financial_types_params' filter
* Added 'woocommerce_civicrm_admin_settings_fields' filter
* Added 'woocommerce_civicrm_address_map' filter
* Added 'woocommerce_civicrm_mapped_location_types' filter
* Added 'woocommerce_civicrm_wc_address_updated' action
* Added 'woocommerce_civicrm_civi_address_updated' action
* Added ‘woocommerce_civicrm_wc_phone_updated’ action
* Added ‘woocommerce_civicrm_civi_phone_updated’ action
* Added ‘woocommerce_civicrm_wc_email_updated’ action
* Added ‘woocommerce_civicrm_civi_email_updated’ action

Feel free to ask for any clarifications :)

### CODE REVIEW

**Comment by rajeshrhino** [comment]
@mecachisenros We have a conflict, so not able to merge the PR. Can you please have a look?

**Comment by mecachisenros** [comment]
@rajeshrhino I'll have a look, I believe is because there's been new commits, ie a PR has been merged recently

**Comment by mecachisenros** [comment]
@rajeshrhino the conflict it's resolved, the issue was that the previous merged PR included commits to `woocommerce_civicrm.php` which no longer exists by that name, now is `woocommerce-civicrm.php`.

I believe those commits by @cdhassell were only addressing the state/province issue #5 which is now addressed in the v2.0 (this PR)

@cdhassell were there any othter issues/changes adressed on your PR?

**Comment by cdhassell** [comment]
No, only "Fix syntax by removing extraneous right paren ")"" which I think was corrected elsewhere.

**Comment by mecachisenros** [comment]
Thank you for clarifying @cdhassell 

@rajeshrhino from my side it should be good to merge

**Comment by rajeshrhino** [comment]
@mecachisenros @cdhassell Thanks for your contributions. We have merged the changes. We will test the plugin again and publish it in WP plugins directory.

**Comment by mecachisenros** [comment]
Thank you @rajeshrhino

**Comment by cdhassell** [comment]
Thanks @mecachisenros!
What is the status of the civicrm extension code?  It is in a separate repository https://github.com/veda-consulting/uk.co.vedaconsulting.module.woocommercecivicrm.
I am getting WC deprecated call notices from that piece.  Does your refactoring also fix that up?

**Comment by mecachisenros** [comment]
@cdhassell no it doesn't fix those notices, that's the last bit missing, I'll give it a go this weekend if I have enough time, and implement it all in this plugin, so we wouldn't need the extra Civi extension/module.

@rajeshrhino @veda-consulting would you agree with integrating/merging the separate module.woocommercecivicrm into this plugin?

**Pull request merged**
